# Project information
site_name: White Whale Docs
site_url: https://whitewhale.finance
site_author: White Whale

# Repository
repo_name: White Whale Docs
repo_url: https://github.com/White-Whale-Defi-Platform/docs
edit_uri: edit/master/docs


plugins:
- search
- literate-nav:
    nav_file: SUMMARY.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/White-Whale-Defi-Platform
      name: White Whale's Github Org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WhiteWhaleTerra
      name: White Whale's Twitter

# Theme
theme:
  name: "material"
  palette:
    scheme: default
    primary: black
    accent: green
  icon:
    logo: wwlogo
  favicon: favicon.png
  custom_dir: assets
  